name: Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Run Trivy scan
        run: trivy fs --exit-code 0 --severity HIGH,CRITICAL --format json . > trivy_report.json

      - name: Export findings to text file
        run: trivy --output "asd.txt" --no-progress --exit-code 1 --severity HIGH,CRITICAL knqyf263/vuln-image:1.2.3
       # jq -r '.Results[] | "Target: \(.Target)\nSeverity: \(.Vulnerabilities[]?.Severity)\nDescription: \(.Vulnerabilities[]?.Description)\n"' trivy_report.json > trivy_report.txt

      - name: Upload Trivy report
        uses: actions/upload-artifact@v2
        with:
          name: trivy-report
          path: trivy_report.txt
